# Generated by Django 2.1.2 on 2018-10-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='saved_model',
            field=models.TextField(default=''),
        ),
    ]
