# Generated by Django 2.1.2 on 2018-10-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0003_repo_stars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/static/images/1.jpg', null=True, upload_to='static/images/')),
            ],
        ),
    ]
