# Generated by Django 2.1.2 on 2018-10-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0005_auto_20181020_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='static/css/'),
        ),
    ]
